config/routes.rb
require 'sidekiq/web'

Feedbin::Application.routes.draw do

  root to: 'site#index'

  mount Sidekiq::Web, at: '/sidekiq'
  mount StripeEvent::Engine, at: '/stripe'

  get :health_check, to: proc {|env| [200, {}, ["OK"]] }
  get :version, to: proc {|env| [200, {}, [ENV["ETAG_VERSION_ID"]]] }

  get :home, to: 'site#home'
  get :apps, to: 'site#apps'

  get :manifest, to: 'site#manifest'

  post '/emails' => 'emails#create'

  match '/404', to: 'errors#not_found', via: :all
  get '/starred/:starred_token', to: 'starred_entries#index', as: 'starred'
  post '/starred/export', to: 'starred_entries#export'
  get '/favicons/:hash', to: 'favicons#index', as: 'favicons'

  get    :signup,         to: 'users#new',           as: 'signup'
  get    :login,          to: 'sessions#new',        as: 'login'
  get    :privacy_policy, to: 'site#privacy_policy', as: 'privacy_policy'
  delete :logout,         to: 'sessions#destroy',    as: 'logout'

  post 'apple_push_notifications/:version/pushPackages/:website_push_id', as: :apple_push_notifications_package, to: 'apple_push_notifications#create', website_push_id: /.*/

  post 'apple_push_notifications/:version/devices/:device_token/registrations/:website_push_id', as: :apple_push_notifications_update, to: 'apple_push_notifications#update', website_push_id: /.*/

  delete 'apple_push_notifications/:version/devices/:device_token/registrations/:website_push_id', as: :apple_push_notifications_delete, to: 'apple_push_notifications#delete', website_push_id: /.*/

  post 'apple_push_notifications/:version/log', as: :apple_push_notifications_log, to: 'apple_push_notifications#log'

  resources :tags,           only: [:index, :show, :update, :destroy]
  resources :billing_events, only: [:show]
  resources :imports
  resources :sessions
  resources :password_resets
  resources :sharing_services, path: 'settings/sharing', only: [:index, :create, :update, :destroy]
  resources :actions, path: 'settings/actions', only: [:index, :create, :new, :update, :destroy, :edit]
  resources :saved_searches

  resources :supported_sharing_services, only: [:create, :destroy, :update] do
    member do
      get :oauth2_pocket_request
      get :oauth2_pocket_response
      get :oauth_response
      get :autocomplete
      post :xauth_request
      match 'share/:entry_id', to: 'supported_sharing_services#share', as: :share, via: [:get, :post]
    end
  end

  resources :subscriptions,  only: [:index, :create, :destroy] do
    collection do
      patch :update_multiple
      delete :destroy_all
    end
    member do
      delete :settings_destroy
    end
  end

  resources :users, id: /.*/ do
    member do
      patch :settings_update, controller: :settings
      patch :view_settings_update, controller: :settings
    end
  end

  resources :feeds, only: [:index, :edit, :create, :update] do
    patch :rename
    resources :entries, only: [:index], controller: :feeds_entries
    collection do
      get :view_unread
      get :view_all
      get :view_starred
      get :auto_update
      get :update_styles
    end
    member do
      match :push, via: [:post, :get]
      post :toggle_updates
      post :toggle_muted
    end
  end

  resources :entries, only: [:show, :index] do
    member do
      post :content
      post :unread_entries, to: 'unread_entries#update'
      post :starred_entries, to: 'starred_entries#update'
      post :mark_as_read, to: 'entries#mark_as_read'
      post :recently_read, to: 'recently_read_entries#create'
      get :push_view
      get :diff
    end
    collection do
      get :starred
      get :unread
      get :preload
      get :search
      get :autocomplete_search
      get :recently_read, to: 'recently_read_entries#index'
      get :updated, to: 'updated_entries#index'
      post :mark_all_as_read
      post :mark_direction_as_read
    end
  end

  get :settings, to: 'settings#settings'
  namespace :settings do
    get :account
    get :billing
    get :import_export
    get :feeds
    get :help
    get :appearance
    post :update_credit_card
    post :mark_favicon_complete
    post :update_plan
    post :font
    post :theme
    post :font_increase
    post :font_decrease
    post :entry_width
  end

  constraints subdomain: 'api' do
    namespace :api, path: nil do
      namespace :v1 do
        match '*path', to: 'api#gone', via: :all
      end
    end
  end

  constraints subdomain: 'api' do
    namespace :api, path: nil do
      namespace :v2 do

        resources :feeds, only: [:show] do
          resources :entries, only: [:index, :show], controller: :feeds_entries
        end

        resources :entry_counts, only: [] do
          collection do
            get :post_frequency
          end
        end

        resources :actions, only: [:index, :create, :update] do
          member do
            get :results
          end
        end

        resources :devices, only: [:create] do
          collection do
            get :test
          end
        end

        resources :users, only: [:create] do
          collection do
            get :info
          end
        end

        resources :subscriptions,         only: [:index, :show, :create, :destroy, :update]
        resources :favicons,              only: [:index]
        resources :tags,                  only: [:index]
        resources :taggings,              only: [:index, :show, :create, :destroy]
        resources :entries,               only: [:index, :show]
        resources :recently_read_entries, only: [:index, :create]
        resources :in_app_purchases,      only: [:create]
        resources :suggested_categories,  only: [:index]
        resources :suggested_feeds,       only: [:index] do
          member do
            post :subscribe
            delete :unsubscribe
          end
        end

        get :authentication, to: 'authentication#index'

        post "subscriptions/:id/update", to: 'subscriptions#update'

        resources :unread_entries, only: [:index, :show, :create]
        delete 'unread_entries', to: 'unread_entries#destroy'
        put 'unread_entries', to: 'unread_entries#create'
        post 'unread_entries/delete', to: 'unread_entries#destroy'

        resources :starred_entries, only: [:index, :show, :create]
        delete 'starred_entries', to: 'starred_entries#destroy'
        put 'starred_entries', to: 'starred_entries#create'
        post 'starred_entries/delete', to: 'starred_entries#destroy'

        resources :updated_entries, only: [:index]
        delete 'updated_entries', to: 'updated_entries#destroy'
        post 'updated_entries/delete', to: 'updated_entries#destroy'

        resources :saved_searches,  only: [:index, :show, :create, :destroy, :update]
        post "saved_searches/:id/update", to: 'saved_searches#update'
      end
    end
  end

end

app/views/shared/_app_settings.html.erb
<div class="entry-button-wrap">
    <div class="dropdown-wrap dropdown-right button-app-settings">
        <div class="entry-button">
            <div class="hamburger-menu-wrap" data-behavior="toggle_dropdown" title="Settings">
                <div class="hamburger-menu"></div>
            </div>
        </div>
        <div class="dropdown-content">
            <ul class="segmented no-border">
                <li><%= link_to 'Settings', settings_path, class: "no-border" %></li>
                <li><%= link_to 'Appearance', settings_appearance_path, class: "no-border" %></li>
                <li><%= link_to 'Feeds', settings_feeds_path %></li>
            </ul>
            <ul class="segmented">
                <li><%= link_to 'Actions', actions_path, class: "no-border" %></li>
                <li><%= link_to 'Sharing', sharing_services_path %></li>
            </ul>
            <ul class="segmented">
                <li><%= link_to 'Account', settings_account_path, class: "no-border" %></li>
                <li><%= link_to 'Billing', settings_billing_path, class: "no-border" %></li>
                <li><%= link_to 'Import/Export', settings_import_export_path %></li>
            </ul>
            <ul class="segmented no-margin">
                <li><%= link_to 'Log Out', logout_path, method: 'delete' %></li>
            </ul>
        </div>
    </div>
</div>

app/views/shared/_entry_settings.html.erb
<div class="entry-settings">
  <div class="setting-wrap font-settings">
    <%= form_tag settings_font_path, remote: true do %>
      <%= select_tag "font", options_for_select(Feedbin::Application.config.fonts, @user.font || 'default'), data: {behavior: 'change_font'} %>
    <% end %>
  </div>
  <div class="setting-wrap">
    <%= link_to settings_font_decrease_path, remote: true, method: :post, class: 'button-decrease-font', title: 'Decrease font size', data: {behavior: 'decrease_font'} do %>
      <%= svg_tag 'icon-smaller-text', size: '48x48' %>
    <% end %>
  </div>
  <div class="setting-wrap">
    <%= link_to settings_font_increase_path, remote: true, method: :post, class: 'button-increase-font', title: 'Increase font size', data: {behavior: 'increase_font'} do %>
      <%= svg_tag 'icon-larger-text', size: '48x48' %>
    <% end %>
  </div>
  <div class="setting-wrap mobile-hide">
    <%= link_to settings_entry_width_path, remote: true, method: :post, class: 'button-entry-width', title: 'Toggle width', data: {behavior: 'entry_width'} do %>
      <%= svg_tag 'icon-entry-width-fixed', size: '34x24' %>
      <%= svg_tag 'icon-entry-width-fluid', size: '34x24' %>
    <% end %>
  </div>
  <div class="setting-wrap mobile-hide">
    <div class="button-full-screen" data-behavior="full_screen" title="Toggle full screen">
      <%= svg_tag 'icon-full-screen-open', size: '34x26' %>
      <%= svg_tag 'icon-full-screen-close', size: '34x26' %>
    </div>
  </div>
  <div class="setting-wrap theme-settings">
    <%= link_to settings_theme_path(theme: 'day'), remote: true, method: :post, class: 'theme-button theme-button-day', title: 'Switch to day theme', data: {behavior: 'switch_theme', theme: 'day'} do %>
      <span class="theme-button-inner"></span>
    <% end %>
    <%= link_to settings_theme_path(theme: 'sunset'), remote: true, method: :post, class: 'theme-button theme-button-sunset', title: 'Switch to sunset theme', data: {behavior: 'switch_theme', theme: 'sunset'} do %>
      <span class="theme-button-inner"></span>
    <% end %>
    <%= link_to settings_theme_path(theme: 'night'), remote: true, method: :post, class: 'theme-button theme-button-night', title: 'Switch to night theme', data: {behavior: 'switch_theme', theme: 'night'} do %>
      <span class="theme-button-inner"></span>
    <% end %>
  </div>
</div>

app/views/shared/_entry_settings_button.html.erb
<div class="entry-button-wrap">
  <button class="entry-button button-settings" data-behavior="show_entry_basement" data-basement-panel="settings_panel" title="Entry Settings">
    <%= svg_tag 'icon-settings', size: '16x16' %>
  </button>
</div>

app/views/shared/_favicons.html.erb
<% if current_user.present? %>
<script>
jQuery(function() {
    $("<link>")
        .appendTo('head')
        .attr({rel: "stylesheet"})
        .attr({href: "<%= url_for(favicons_path(hash: current_user.get_favicon_hash, format: :css)) %>"});
});
</script>
<% end %>

app/views/shared/_feeds_toolbar.erb
<div class="feeds-toolbar">
  <table cellpadding="0">
    <tbody>
      <tr>
        <td>
          <%= render partial: 'shared/buttons/tag', locals: {feed: nil, tags: nil, tag: nil} %>
        </td>
        <td>
          <%= render partial: 'shared/buttons/mark_all_as_read', locals: {type: nil, data: nil} %>
        </td>
        <td>
          <%= render partial: 'shared/buttons/unsubscribe', locals: {feed: nil} %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/shared/_fonts.html.erb
<% if current_user.present? && ENV['FONT_STYLESHEET'].present? %>
<script>
jQuery(function() {
    $("<link>")
        .appendTo('head')
        .attr({rel: "stylesheet"})
        .attr({href: "<%= ENV['FONT_STYLESHEET'] %>"});
});
</script>
<% end %>

app/views/shared/_full_screen_button.html.erb
<button class="entry-button button-full-screen" data-behavior="full_screen" title="Close full screen">
    <%= svg_tag 'icon-full-screen-close-small', size: '16x16' %>
</button>

app/views/shared/_instagram_embed.html.erb
<script async defer src="//platform.instagram.com/en_US/embeds.js"></script>

app/views/shared/_messages.html.erb
<% @messages.each do |message| %>
  <%= message.sanitize.html_safe %>.
<% end %>

app/views/shared/_readability_loading.html.erb
<div class="hide" data-behavior="readability_loading">
    <p class="readability-loading entry-callout">Loading Readability…</p>
</div>

app/views/shared/_svg.html.erb
<svg class="hide">
  <defs>
    <% Dir.glob("#{Rails.root}/app/assets/svg/*.svg").sort.each do |svg| %>
      <g id="<%= File.basename(svg, ".svg") %>">
        <%= File.read(svg).html_safe %>
      </g>
    <% end %>
  </defs>
</svg>

app/views/shared/_twitter_embed.html.erb
<% if current_user.present? %>
<script>window.twttr = (function (d, s, id) {
  var t, js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src= "https://platform.twitter.com/widgets.js";
  fjs.parentNode.insertBefore(js, fjs);
  return window.twttr || (t = { _e: [], ready: function (f) { t._e.push(f) } });
}(document, "script", "twitter-wjs"));</script>
<% end %>

app/views/shared/_update_feeds.js.erb
feedbin.updateFeeds('<%= j render partial: 'feeds/feeds', locals: {collections: @feed_data[:collections], saved_searches: @feed_data[:saved_searches], tags: @feed_data[:tags], feeds: @feed_data[:feeds]} %>');
feedbin.count_data = <%= @feed_data[:count_data].to_json.html_safe %>;
feedbin.data.feed_order = <%= @feed_data[:feed_order].to_json.html_safe %>;
feedbin.Counts.get().update(feedbin.count_data);
feedbin.applyCounts(false);
feedbin.draggable();
feedbin.droppable();

app/views/shared/_update_styles.html.erb
<script>
jQuery(function() {
    $("<link>")
        .appendTo('head')
        .attr({rel: "stylesheet"})
        .attr({href: "<%= url_for(update_styles_feeds_path(format: :css)) %>"});
});
</script>