config/routes.rb
require 'sidekiq/web'

Feedbin::Application.routes.draw do

  root to: 'site#index'

  mount Sidekiq::Web, at: '/sidekiq'
  mount StripeEvent::Engine, at: '/stripe'

  get :health_check, to: proc {|env| [200, {}, ["OK"]] }
  get :version, to: proc {|env| [200, {}, [ENV["ETAG_VERSION_ID"]]] }

  get :home, to: 'site#home'
  get :apps, to: 'site#apps'

  get :manifest, to: 'site#manifest'

  post '/emails' => 'emails#create'

  match '/404', to: 'errors#not_found', via: :all
  get '/starred/:starred_token', to: 'starred_entries#index', as: 'starred'
  post '/starred/export', to: 'starred_entries#export'
  get '/favicons/:hash', to: 'favicons#index', as: 'favicons'

  get    :signup,         to: 'users#new',           as: 'signup'
  get    :login,          to: 'sessions#new',        as: 'login'
  get    :privacy_policy, to: 'site#privacy_policy', as: 'privacy_policy'
  delete :logout,         to: 'sessions#destroy',    as: 'logout'

  post 'apple_push_notifications/:version/pushPackages/:website_push_id', as: :apple_push_notifications_package, to: 'apple_push_notifications#create', website_push_id: /.*/

  post 'apple_push_notifications/:version/devices/:device_token/registrations/:website_push_id', as: :apple_push_notifications_update, to: 'apple_push_notifications#update', website_push_id: /.*/

  delete 'apple_push_notifications/:version/devices/:device_token/registrations/:website_push_id', as: :apple_push_notifications_delete, to: 'apple_push_notifications#delete', website_push_id: /.*/

  post 'apple_push_notifications/:version/log', as: :apple_push_notifications_log, to: 'apple_push_notifications#log'

  resources :tags,           only: [:index, :show, :update, :destroy]
  resources :billing_events, only: [:show]
  resources :imports
  resources :sessions
  resources :password_resets
  resources :sharing_services, path: 'settings/sharing', only: [:index, :create, :update, :destroy]
  resources :actions, path: 'settings/actions', only: [:index, :create, :new, :update, :destroy, :edit]
  resources :saved_searches

  resources :supported_sharing_services, only: [:create, :destroy, :update] do
    member do
      get :oauth2_pocket_request
      get :oauth2_pocket_response
      get :oauth_response
      get :autocomplete
      post :xauth_request
      match 'share/:entry_id', to: 'supported_sharing_services#share', as: :share, via: [:get, :post]
    end
  end

  resources :subscriptions,  only: [:index, :create, :destroy] do
    collection do
      patch :update_multiple
      delete :destroy_all
    end
    member do
      delete :settings_destroy
    end
  end

  resources :users, id: /.*/ do
    member do
      patch :settings_update, controller: :settings
      patch :view_settings_update, controller: :settings
    end
  end

  resources :feeds, only: [:index, :edit, :create, :update] do
    patch :rename
    resources :entries, only: [:index], controller: :feeds_entries
    collection do
      get :view_unread
      get :view_all
      get :view_starred
      get :auto_update
      get :update_styles
    end
    member do
      match :push, via: [:post, :get]
      post :toggle_updates
      post :toggle_muted
    end
  end

  resources :entries, only: [:show, :index] do
    member do
      post :content
      post :unread_entries, to: 'unread_entries#update'
      post :starred_entries, to: 'starred_entries#update'
      post :mark_as_read, to: 'entries#mark_as_read'
      post :recently_read, to: 'recently_read_entries#create'
      get :push_view
      get :diff
    end
    collection do
      get :starred
      get :unread
      get :preload
      get :search
      get :autocomplete_search
      get :recently_read, to: 'recently_read_entries#index'
      get :updated, to: 'updated_entries#index'
      post :mark_all_as_read
      post :mark_direction_as_read
    end
  end

  get :settings, to: 'settings#settings'
  namespace :settings do
    get :account
    get :billing
    get :import_export
    get :feeds
    get :help
    get :appearance
    post :update_credit_card
    post :mark_favicon_complete
    post :update_plan
    post :font
    post :theme
    post :font_increase
    post :font_decrease
    post :entry_width
  end

  constraints subdomain: 'api' do
    namespace :api, path: nil do
      namespace :v1 do
        match '*path', to: 'api#gone', via: :all
      end
    end
  end

  constraints subdomain: 'api' do
    namespace :api, path: nil do
      namespace :v2 do

        resources :feeds, only: [:show] do
          resources :entries, only: [:index, :show], controller: :feeds_entries
        end

        resources :entry_counts, only: [] do
          collection do
            get :post_frequency
          end
        end

        resources :actions, only: [:index, :create, :update] do
          member do
            get :results
          end
        end

        resources :devices, only: [:create] do
          collection do
            get :test
          end
        end

        resources :users, only: [:create] do
          collection do
            get :info
          end
        end

        resources :subscriptions,         only: [:index, :show, :create, :destroy, :update]
        resources :favicons,              only: [:index]
        resources :tags,                  only: [:index]
        resources :taggings,              only: [:index, :show, :create, :destroy]
        resources :entries,               only: [:index, :show]
        resources :recently_read_entries, only: [:index, :create]
        resources :in_app_purchases,      only: [:create]
        resources :suggested_categories,  only: [:index]
        resources :suggested_feeds,       only: [:index] do
          member do
            post :subscribe
            delete :unsubscribe
          end
        end

        get :authentication, to: 'authentication#index'

        post "subscriptions/:id/update", to: 'subscriptions#update'

        resources :unread_entries, only: [:index, :show, :create]
        delete 'unread_entries', to: 'unread_entries#destroy'
        put 'unread_entries', to: 'unread_entries#create'
        post 'unread_entries/delete', to: 'unread_entries#destroy'

        resources :starred_entries, only: [:index, :show, :create]
        delete 'starred_entries', to: 'starred_entries#destroy'
        put 'starred_entries', to: 'starred_entries#create'
        post 'starred_entries/delete', to: 'starred_entries#destroy'

        resources :updated_entries, only: [:index]
        delete 'updated_entries', to: 'updated_entries#destroy'
        post 'updated_entries/delete', to: 'updated_entries#destroy'

        resources :saved_searches,  only: [:index, :show, :create, :destroy, :update]
        post "saved_searches/:id/update", to: 'saved_searches#update'
      end
    end
  end

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  has_many :subscriptions
  has_many :entries
  has_many :users, through: :subscriptions
  has_many :unread_entries
  has_many :starred_entries
  has_many :feed_stats

  has_many :taggings
  has_many :tags, through: :taggings

  before_create :set_host

  attr_accessor :count, :tags

  def tag(names, user, delete_existing = true)
    taggings = []
    if delete_existing
      Tagging.destroy_all(user_id: user, feed_id: self.id)
    end
    names.split(",").map do |name|
      name = name.strip
      unless name.blank?
        tag = Tag.where(name: name.strip).first_or_create!
        taggings << self.taggings.where(user: user, tag: tag).first_or_create!
      end
    end
    taggings
  end

  def self.create_from_feedjira(feed, site_url)
    feed.url = site_url
    feed_record = self.create!(feed: feed)
    ActiveRecord::Base.transaction do
      feed.entries.each do |entry|
        feed_record.entries.create!(entry: entry)
      end
    end
    feed_record
  end

  def feed=(feed)
    self.etag          = feed.etag
    self.last_modified = feed.last_modified
    self.title         = feed.title
    self.feed_url      = feed.feed_url
    self.site_url      = feed.url
  end

  def check
    options = {}
    unless last_modified.blank?
      options[:if_modified_since] = last_modified
    end
    unless etag.blank?
      options[:if_none_match] = etag
    end
    feed_fetcher = FeedFetcher.new(feed_url)
    feed_fetcher.fetch_and_parse(options, feed_url)
  end

  def self.include_user_title
    feeds = select('feeds.*, subscriptions.title AS user_title')
    feeds.map do |feed|
      if feed.user_title
        feed.override_title(feed.user_title)
      end
      feed.title ||= '(No title)'
      feed
    end
    feeds.sort_by {|feed| feed.title.try(:downcase)}
  end

  def string_id
    self.id.to_s
  end

  def set_host
    begin
      self.host = URI::parse(self.site_url).host
      FaviconFetcher.perform_async(self.host)
    rescue Exception
      Rails.logger.info { "Failed to set host for feed: %s" %  self.site_url}
    end
  end

  def override_title(title)
    @original_title = self.title
    self.title=(title)
  end

  def original_title
    @original_title or self.title
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
  def timeago(time)
    if time.nil?
      'N/A'
    else
      content_tag(:time, time.to_s(:feed), datetime: time.utc.iso8601, class: 'timeago', title: "Last updated: #{time.to_s(:feed)}" )
    end
  end
end

app/views/settings/appearance.html.erb
<div class="settings-content-inner">
  <div class="settings-outer">
    <h2>Appearance</h2>
  </div>

  <div class="inset">

    <div class="preview-group">
      <div class="inset-content">
        <h4 class="group-header">Preview</h4>
      </div>
      <ul class="control-group">
        <li class="theme-background <%= @classes %>" data-behavior="entries_max_width class_target">

          <div data-behavior="preview_min_height">
            <div class="entries-wrap">
              <div class="entries">
                <ul>
                  <li data-behavior="responsive_text_size">
                    <span class="wrap">
                      <span class="entries-inner-wrap">
                        <span class="favicon-wrap">
                          <span class="favicon" style="background: url(https://www.google.com/s2/favicons?domain=foodinjars.com);"></span>
                        </span>
                        <p class="feed-title"><span class="title-inner">Food in Jars</span></p>
                        <time class="time">1h</time>
                        <span class="title-wrap">
                          <h2 class="title">
                            <span class="favicon-wrap">
                              <span class="favicon" style="background: url(https://www.google.com/s2/favicons?domain=foodinjars.com);"></span>
                            </span>
                            Spicy Peach and Yellow Tomato Jam
                          </h2>
                          <p class="body">I made this jam back before my trip to Portland and have been meaning to share it&hellip;</p>
                        </span>
                      </span>
                    </span>
                  </li>
                </ul>
              </div>
            </div>
          </div>

        </li>
      </ul>
    </div>

    <%= form_for @user, url: settings_update_user_path(@user) do |f| %>
      <%= hidden_field_tag :redirect_to, settings_appearance_url %>

      <div class="inset-content">
        <h4 class="group-header">Theme</h4>
      </div>
      <ul class="control-group control-group-form">
        <li>
          <%= f.radio_button(:theme, "day", {checked: @user.theme.nil? || @user.theme === 'day', data: {behavior: 'appearance_radio', setting: 'theme'}}) %>
          <%= f.label(:theme_day, "Day") %>
        </li>
        <li>
          <%= f.radio_button(:theme, "sunset", {data: {behavior: 'appearance_radio', setting: 'theme'}}) %>
          <%= f.label(:theme_sunset, "Sunset") %>
        </li>
        <li>
          <%= f.radio_button(:theme, "night", {data: {behavior: 'appearance_radio', setting: 'theme'}}) %>
          <%= f.label(:theme_night, "Night") %>
        </li>
      </ul>

      <div class="inset-content">
        <h4 class="group-header">Summary Display</h4>
      </div>
      <ul class="control-group control-group-form">
        <li>
          <%= f.radio_button(:entries_display, "block", {checked: @user.entries_display.nil? || @user.entries_display === 'block', data: {behavior: 'appearance_radio', setting: 'entries-display'}}) %>
          <%= f.label(:entries_display_block, "Default") %>
        </li>
        <li>
          <%= f.radio_button(:entries_display, "inline", {data: {behavior: 'appearance_radio', setting: 'entries-display'}}) %>
          <%= f.label(:entries_display_inline, "Inline") %>
        </li>
      </ul>

      <div class="inset-content">
        <h4 class="group-header">Interface Elements</h4>
      </div>
      <ul class="control-group control-group-form">
        <li>
          <%= f.check_box :entries_feed, {checked: @user.entries_feed.nil? || @user.setting_on?(:entries_feed), data: {behavior: 'appearance_checkbox', setting: 'entries-feed'} } %>
          <%= f.label :entries_feed do %>
            Feed Name <span class="slider-checkbox"></span>
          <% end %>
        </li>
        <li>
          <%= f.check_box :entries_time, {checked: @user.entries_time.nil? || @user.setting_on?(:entries_time), data: {behavior: 'appearance_checkbox', setting: 'entries-time'} } %>
          <%= f.label :entries_time do %>
            Date <span class="slider-checkbox"></span>
          <% end %>
        </li>
        <li>
          <%= f.check_box :entries_body, {checked: @user.entries_body.nil? || @user.setting_on?(:entries_body), data: {behavior: 'appearance_checkbox', setting: 'entries-body'} } %>
          <%= f.label :entries_body do %>
            Summary <span class="slider-checkbox"></span>
          <% end %>
        </li>
      </ul>

      <div class="description-inset">
        <%= f.submit "Save", class: 'button-plain no-margin' %>
      </div>

    <% end %>
  </div>
</div>

app/views/settings/billing.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "https://js.stripe.com/v1/" %>
<% end %>

<div class="settings-content-inner">
  <div class="settings-outer">
    <h2>Billing</h2>
  </div>


  <% if ENV['STRIPE_API_KEY'] %>
    <% if @user.plan.stripe_id == 'trial' %>
      <div class="settings-outer">
        <% if @user.days_left <= 0 %>
          <p>Your trial has ended. Subscribe now to continue using Feedbin.</p>
        <% else %>
          <p>Your trial period will end in <strong><%= pluralize(@user.days_left, 'day') %></strong>. Subscribe now to continue using Feedbin uninterrupted.</p>
        <% end %>
        <div data-behavior="stripe_error" class="alert alert-error hide"></div>
      </div>
      <div class="inset">
        <%= form_for @user, html: { data: { behavior: 'credit_card_form' } } do |f| %>
          <%= f.hidden_field :stripe_token, data: { behavior: 'stripe_token' } %>
          <%= hidden_field_tag :redirect_to, settings_billing_url %>

          <div class="inset-content">
            <h4 class="group-header">Subscribe</h4>
          </div>
          <% if @user.stripe_token %>
            <p>Credit card acceptance is pending.</p>
          <% else %>
            <%= render partial: 'shared/credit_card_form' %>
          <% end %>

          <ul class="control-group control-group-form">
          <% @plans.each do |plan| %>
            <li>
              <% options = plan.stripe_id == 'basic-yearly-2' ? {checked: true, id: dom_id(plan)} : {id: dom_id(plan)} %>
              <%= f.radio_button :plan_id, plan.id, options %>
              <%= label_tag nil, for: dom_id(plan) do %>
                <%= number_to_currency(plan.price, precision: 0) %>/<%= plan.name.gsub(/ly$/, '').downcase %>
              <% end %>
            </li>
          <% end %>
          </ul>

          <div class="description-inset">
            <%= f.submit "Subscribe", class: 'button-plain' %>
          </div>

        <% end %>
      </div>

    <% else %>
      <div class="settings-outer">
        <div data-behavior="stripe_error" class="alert alert-error hide"></div>
      </div>

      <div class="inset">
        <%= form_tag settings_update_credit_card_path, data: { behavior: 'credit_card_form' } do %>
          <%= hidden_field_tag :stripe_token, nil, data: { behavior: 'stripe_token' } %>
          <div class="inset-content">
            <h4 class="group-header">Update Billing Info</h4>
          </div>

          <%= render partial: 'shared/credit_card_form' %>

          <div class="description-inset">
            <%= submit_tag "Update Billing", class: "button-plain no-margin" %>
          </div>

        <% end %>
      </div>

      <div class="inset">
        <div class="inset-content">
          <h4 class="group-header">Change Your Plan</h4>
        </div>
        <div class="table-wrap">
          <table class="table table-rounded" style="margin-bottom: 0;">
            <% @plans.each do |plan| %>
              <tr>
                <td><%= plan.name %></td>
                <td><%= number_to_currency(plan.price) %>/<%= plan.name %></td>
                <td>
                  <% if @user.plan.id == plan.id %>
                    Your plan
                  <% else %>
                    <%= form_tag settings_update_plan_path, data: { behavior: 'change_plan' }, class: 'no-margin' do %>
                      <%= hidden_field_tag 'plan', plan.id %>
                      <%= button_tag 'Switch to this plan', class: 'button button-link' %>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </table>
        </div>
        <p class="control-group-description">Plan changes are pro-rated.</p>

        <div class="inset-content">
          <h4 class="group-header">Payment History</h4>
        </div>
        <div class="table-wrap">
          <table class="table table-rounded">
            <% if @next_payment_date %>
              <tr>
                <td><time datetime="<%= @next_payment_date.to_s(:date) %>"><%= @next_payment_date.to_s(:date) %></time></td>
                <td>&nbsp;</td>
                <td><span class="extra-muted">Scheduled</span></td>
              </tr>
            <% end %>
            <% @billing_events.each do |invoice| %>
            <tr>
              <td><%= Time.at(invoice.details.data.object.created).to_s(:date) %></td>
              <td><%= invoice.details.data.object.currency.upcase %> <%= number_to_currency(invoice.details.data.object.amount.to_f / 100) %></td>
              <td><%= link_to 'Receipt', invoice %></td>
            </tr>
            <% end %>
          </table>
        </div>
      </div>

      <div class="inset">
        <div class="inset-content">
          <h4 class="group-header">Receipt Info</h4>
        </div>

        <%= form_for @user, url: settings_update_user_path(@user) do |f| %>
          <%= hidden_field_tag :redirect_to, settings_billing_url %>
          <ul class="control-group control-group-form">
            <li>
              <%= f.text_area :receipt_info, rows: 3 %>
            </li>
          </ul>
          <p class="control-group-description">This will show up on your receipt. Useful for VAT, address etc&hellip;</p>
          <div class="description-inset">
            <%= f.submit "Save Info", class: "button-plain  no-margin" %>
          </div>
        <% end %>
      </div>

    <% end %>
  <% else %>
    <p>Billing disabled. <code>STRIPE_API_KEY</code> and <code>STRIPE_PUBLIC_KEY</code> are missing.</p>
  <% end %>
</div>

app/views/settings/feeds.html.erb
<div class="settings-content-inner">

    <%= form_tag update_multiple_subscriptions_path, method: :patch, autocomplete: 'off' do %>
    <input type="hidden" name="operation" value="" />

    <div class="feed-settings">
        <div class="clearfix">
            <div class="half float-right">
                <input type="text" class="feed-search" data-behavior="feed_search" placeholder="Search Feeds" />
            </div>
            <div class="half por">
                <h2>Feeds</h2>
            </div>
        </div>

        <div class="feed-controls clearfix">
            <div class="half text-right float-right">
                <div class="dropdown-wrap dropdown-right feed-dropdown">
                    <button class="feeds-toolbar-button button-caret no-margin" data-behavior="toggle_dropdown sort_label">Sort by name</button>
                    <div class="dropdown-content">
                        <ul>
                            <li data-behavior="sort_feeds" data-value="name"><span>Sort by name</span></li>
                            <li data-behavior="sort_feeds" data-value="last-updated"><span>Sort by last updated</span></li>
                            <li data-behavior="sort_feeds" data-value="volume"><span>Sort by volume</span></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="half por">
                <input type="checkbox" class="feeds-checkbox" data-behavior="toggle_checked" />
                <div class="dropdown-wrap feed-dropdown">
                    <button class="feeds-toolbar-button button-caret" data-behavior="toggle_dropdown feed_actions">Actions</button>
                    <div class="dropdown-content">
                        <ul>
                            <li data-operation="unsubscribe"><span>Unsubscribe</span></li>
                            <li data-operation="show_updates"><span class="no-border">Show updates on articles</span></li>
                            <li data-operation="hide_updates"><span>Hide updates on articles</span></li>
                            <li data-operation="mute"><span class="no-border">Mute Feed</span></li>
                            <li data-operation="unmute"><span>Unmute Feed</span></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="feed-form-wrap">
        <ul class="pill-list feed-form sortable"  data-behavior="search_results">
            <% @subscriptions.each do |subscription| %>
                <% present subscription do |subscription_presenter| %>
                    <%= fields_for "subscriptions[]", subscription do |f| %>
                        <li data-sort-name="<%= subscription.title.downcase %>" data-sort-last-updated="<%= subscription.try(:last_published_entry).try(:to_time).try(:to_i) %>" data-sort-post-volume="<%= subscription.post_volume %>">
                            <div class="checkbox-wrap">
                                <%= check_box_tag "subscription_ids[]", subscription.id, false, id: "subscription_checkbox_#{subscription.id}" %>
                            </div>
                            <div class="update-wrap">
                                <%= link_to '', toggle_updates_feed_path(subscription.feed), remote: true, method: :post, class: "update-icon #{subscription.show_updates? ? 'on' : ''}", data: {toggle: {class: 'on', title: ['Show updates on articles', 'Hide updates on articles']}}, title: (subscription.show_updates?) ? 'Hide updates on articles' : 'Show updates on articles'   %>
                            </div>
                            <div class="mute-wrap">
                                <%= link_to '', toggle_muted_feed_path(subscription.feed), remote: true, method: :post, class: "mute-icon #{subscription.muted? ? '' : 'on'}", data: {toggle: {class: 'on', title: ['Mute', 'Unmute']}}, title: (subscription.muted?) ? 'Unmute' : 'Mute' %>
                            </div>
                            <label class="subscription-title" for="subscription_checkbox_<%= subscription.id %>">
                                <a href="<%= subscription.feed_url %>" title="Feed URL" class="favicon-container">
                                    <%= subscription_presenter.favicon(subscription.host) %>
                                </a>
                                <%= subscription.title %>
                            </label>
                            <div class="last-updated-wrap">
                                <%= timeago(subscription.last_published_entry) %>
                            </div>
                            <div class="canvas-wrap">
                                <%= content_tag :canvas, '', width: 97, height: 20, data: { values: subscription.entries_count }, title: "Post frequency (#{number_with_delimiter(subscription.post_volume)} posts in the last 30 days)" %>
                            </div>
                        </li>
                    <% end %>
                <% end %>
            <% end %>
        </ul>
    </div>

    <% end %>
</div>

app/views/settings/import_export.html.erb
<div class="settings-content-inner">
    <div class="settings-outer">
        <h2>Import/Export</h2>
    </div>

    <div class="inset">

        <div class="inset-content">
            <h4 class="group-header">Import</h4>
        </div>

        <% if ENV['AWS_ACCESS_KEY_ID'] %>
        <%= direct_upload_form_for @uploader do |f| %>
        <ul class="control-group">
            <li>
                <%= f.file_field :upload %>
            </li>
        </ul>
        <p class="control-group-description">You can import OPML files. Import is done in the background so you may not see every subscription or starred item right away.</p>

        <div class="description-inset">
            <%= f.submit "Import", class: "button-plain no-margin" %>
        </div>

        <% end %>

        <% else %>
            <p class="control-group-description">Import disabled. <code>AWS_ACCESS_KEY_ID</code>, <code>AWS_SECRET_ACCESS_KEY</code> and <code>AWS_S3_BUCKET</code> are missing.</p>
        <% end %>
    </div>

    <div class="inset">
        <div class="inset-content">
            <h4 class="group-header">Export</h4>
        </div>
        <ul class="pill-list">
            <li>
                <%= form_tag subscriptions_path(format: :xml), method: :get do %>
                    Subscriptions
                    <%= select_tag :tag, options_for_select(@download_options), style: "width: 150px; margin-left: 10px;" %>
                    <button class="button-plain no-margin pull-right no-top-margin">Download</button>
                <% end %>
            </li>
            <% if @user.starred_entries.exists? %>
                <li>
                    Starred Articles <%= link_to "Export", starred_export_path, method: :post, class: 'pull-right' %>
                </li>
            <% end %>
        </ul>

        <% if @user.starred_entries.exists? %>
            <p class="control-group-description">A link will be emailed to you.</p>
        <% end %>

    </div>

</div>

app/views/settings/settings.html.erb
<div class="settings-content-inner">

    <div class="settings-outer">
        <h2>Settings</h2>
    </div>

    <div class="inset">

        <%= form_for @user, url: settings_update_user_path(@user) do |f| %>

            <div class="inset-content">
                <h4 class="group-header">Unread Sort</h4>
            </div>
            <ul class="control-group control-group-form">
                <li>
                    <%= f.radio_button(:entry_sort, "DESC", {checked: @user.entry_sort.nil? || @user.entry_sort === 'DESC'}) %>
                    <%= f.label('entry_sort_desc', "Newest First") %>
                </li>
                <li>
                    <%= f.radio_button(:entry_sort, "ASC") %>
                    <%= f.label('entry_sort_asc', "Oldest First") %>
                </li>
            </ul>

            <ul class="control-group control-group-form">
                <li>
                    <%= f.check_box :mark_as_read_confirmation %>
                    <%= f.label :mark_as_read_confirmation do %>
                        Ask before marking all as read <span class="slider-checkbox"></span>
                    <% end %>
                </li>
                <li>
                    <%= f.check_box :sticky_view_inline %>
                    <%= f.label :sticky_view_inline do %>
                        Sticky Readability <span class="slider-checkbox"></span>
                    <% end %>
                </li>
            </ul>
            <p class="control-group-description">
                Use last Readability setting per feed
            </p>

            <ul class="control-group control-group-form">
                <li>
                    <%= f.check_box :show_unread_count %>
                    <%= f.label :show_unread_count do %>
                        Show unread count in title <span class="slider-checkbox"></span>
                    <% end %>
                </li>
                <li>
                    <%= f.check_box :hide_recently_read %>
                    <%= f.label :hide_recently_read do %>
                        Hide Recently Read section <span class="slider-checkbox"></span>
                    <% end %>
                </li>
                <li>
                    <%= f.check_box :hide_updated %>
                    <%= f.label :hide_updated do %>
                        Hide Updated section <span class="slider-checkbox"></span>
                    <% end %>
                </li>
            </ul>

            <ul class="control-group control-group-form">
                <li>
                    <%= f.check_box :starred_feed_enabled %>
                    <%= f.label :starred_feed_enabled do %>
                        Enable starred article feed <span class="slider-checkbox"></span>
                    <% end %>
                </li>
            </ul>
            <% if @user.setting_on?(:starred_feed_enabled) %>
                <p class="control-group-description">
                    Your starred feed: <a href="<%= starred_url(@user.starred_token, format: :xml) %>" style="word-break: break-all;"><%= starred_url(@user.starred_token, format: :xml) %></a>
                </p>
            <% end %>

            <div class="description-inset">
                <%= f.submit "Save", class: 'button-plain no-margin' %>
            </div>

        <% end %>
    </div>

    <div class="inset">

        <%= form_for @user, url: settings_update_user_path(@user) do |f| %>

            <div class="inset-content">
                <h4 class="group-header">Advanced</h4>
            </div>

            <ul class="control-group control-group-form">
                <li>
                    <%= f.check_box :disable_image_proxy %>
                    <%= f.label :disable_image_proxy do %>
                        Disable image proxy <span class="slider-checkbox"></span>
                    <% end %>
                </li>
            </ul>
            <p class="control-group-description">
                A TLS enabled image proxy is used to prevent <a href="https://developer.mozilla.org/en-US/docs/Security/MixedContent">mixed content</a> warnings. You can turn it off if you experience image loading issues.
            </p>

            <div class="description-inset">
                <%= f.submit "Save", class: 'button-plain no-margin' %>
            </div>

        <% end %>
    </div>

    <div class="description-inset icon-email">
        <h3>Subscribe via Email</h3>
        <p class="muted">You can subscribe to any website that publishes a feed by sending an email to this secret address. The body of the email should only contain the URL to the website or feed.</p>
        <p class="subscribe-email"><a href="mailto:subscribe+<%= @user.inbound_email_token %>@subscribe.feedbin.com">subscribe+<%= @user.inbound_email_token %>@subscribe.feedbin.com</a></p>
    </div>

</div>