config/routes.rb
require 'sidekiq/web'

Feedbin::Application.routes.draw do

  root to: 'site#index'

  mount Sidekiq::Web, at: '/sidekiq'
  mount StripeEvent::Engine, at: '/stripe'

  get :health_check, to: proc {|env| [200, {}, ["OK"]] }
  get :version, to: proc {|env| [200, {}, [ENV["ETAG_VERSION_ID"]]] }

  get :home, to: 'site#home'
  get :apps, to: 'site#apps'

  get :manifest, to: 'site#manifest'

  post '/emails' => 'emails#create'

  match '/404', to: 'errors#not_found', via: :all
  get '/starred/:starred_token', to: 'starred_entries#index', as: 'starred'
  post '/starred/export', to: 'starred_entries#export'
  get '/favicons/:hash', to: 'favicons#index', as: 'favicons'

  get    :signup,         to: 'users#new',           as: 'signup'
  get    :login,          to: 'sessions#new',        as: 'login'
  get    :privacy_policy, to: 'site#privacy_policy', as: 'privacy_policy'
  delete :logout,         to: 'sessions#destroy',    as: 'logout'

  post 'apple_push_notifications/:version/pushPackages/:website_push_id', as: :apple_push_notifications_package, to: 'apple_push_notifications#create', website_push_id: /.*/

  post 'apple_push_notifications/:version/devices/:device_token/registrations/:website_push_id', as: :apple_push_notifications_update, to: 'apple_push_notifications#update', website_push_id: /.*/

  delete 'apple_push_notifications/:version/devices/:device_token/registrations/:website_push_id', as: :apple_push_notifications_delete, to: 'apple_push_notifications#delete', website_push_id: /.*/

  post 'apple_push_notifications/:version/log', as: :apple_push_notifications_log, to: 'apple_push_notifications#log'

  resources :tags,           only: [:index, :show, :update, :destroy]
  resources :billing_events, only: [:show]
  resources :imports
  resources :sessions
  resources :password_resets
  resources :sharing_services, path: 'settings/sharing', only: [:index, :create, :update, :destroy]
  resources :actions, path: 'settings/actions', only: [:index, :create, :new, :update, :destroy, :edit]
  resources :saved_searches

  resources :supported_sharing_services, only: [:create, :destroy, :update] do
    member do
      get :oauth2_pocket_request
      get :oauth2_pocket_response
      get :oauth_response
      get :autocomplete
      post :xauth_request
      match 'share/:entry_id', to: 'supported_sharing_services#share', as: :share, via: [:get, :post]
    end
  end

  resources :subscriptions,  only: [:index, :create, :destroy] do
    collection do
      patch :update_multiple
      delete :destroy_all
    end
    member do
      delete :settings_destroy
    end
  end

  resources :users, id: /.*/ do
    member do
      patch :settings_update, controller: :settings
      patch :view_settings_update, controller: :settings
    end
  end

  resources :feeds, only: [:index, :edit, :create, :update] do
    patch :rename
    resources :entries, only: [:index], controller: :feeds_entries
    collection do
      get :view_unread
      get :view_all
      get :view_starred
      get :auto_update
      get :update_styles
    end
    member do
      match :push, via: [:post, :get]
      post :toggle_updates
      post :toggle_muted
    end
  end

  resources :entries, only: [:show, :index] do
    member do
      post :content
      post :unread_entries, to: 'unread_entries#update'
      post :starred_entries, to: 'starred_entries#update'
      post :mark_as_read, to: 'entries#mark_as_read'
      post :recently_read, to: 'recently_read_entries#create'
      get :push_view
      get :diff
    end
    collection do
      get :starred
      get :unread
      get :preload
      get :search
      get :autocomplete_search
      get :recently_read, to: 'recently_read_entries#index'
      get :updated, to: 'updated_entries#index'
      post :mark_all_as_read
      post :mark_direction_as_read
    end
  end

  get :settings, to: 'settings#settings'
  namespace :settings do
    get :account
    get :billing
    get :import_export
    get :feeds
    get :help
    get :appearance
    post :update_credit_card
    post :mark_favicon_complete
    post :update_plan
    post :font
    post :theme
    post :font_increase
    post :font_decrease
    post :entry_width
  end

  constraints subdomain: 'api' do
    namespace :api, path: nil do
      namespace :v1 do
        match '*path', to: 'api#gone', via: :all
      end
    end
  end

  constraints subdomain: 'api' do
    namespace :api, path: nil do
      namespace :v2 do

        resources :feeds, only: [:show] do
          resources :entries, only: [:index, :show], controller: :feeds_entries
        end

        resources :entry_counts, only: [] do
          collection do
            get :post_frequency
          end
        end

        resources :actions, only: [:index, :create, :update] do
          member do
            get :results
          end
        end

        resources :devices, only: [:create] do
          collection do
            get :test
          end
        end

        resources :users, only: [:create] do
          collection do
            get :info
          end
        end

        resources :subscriptions,         only: [:index, :show, :create, :destroy, :update]
        resources :favicons,              only: [:index]
        resources :tags,                  only: [:index]
        resources :taggings,              only: [:index, :show, :create, :destroy]
        resources :entries,               only: [:index, :show]
        resources :recently_read_entries, only: [:index, :create]
        resources :in_app_purchases,      only: [:create]
        resources :suggested_categories,  only: [:index]
        resources :suggested_feeds,       only: [:index] do
          member do
            post :subscribe
            delete :unsubscribe
          end
        end

        get :authentication, to: 'authentication#index'

        post "subscriptions/:id/update", to: 'subscriptions#update'

        resources :unread_entries, only: [:index, :show, :create]
        delete 'unread_entries', to: 'unread_entries#destroy'
        put 'unread_entries', to: 'unread_entries#create'
        post 'unread_entries/delete', to: 'unread_entries#destroy'

        resources :starred_entries, only: [:index, :show, :create]
        delete 'starred_entries', to: 'starred_entries#destroy'
        put 'starred_entries', to: 'starred_entries#create'
        post 'starred_entries/delete', to: 'starred_entries#destroy'

        resources :updated_entries, only: [:index]
        delete 'updated_entries', to: 'updated_entries#destroy'
        post 'updated_entries/delete', to: 'updated_entries#destroy'

        resources :saved_searches,  only: [:index, :show, :create, :destroy, :update]
        post "saved_searches/:id/update", to: 'saved_searches#update'
      end
    end
  end

end

app/views/shared/buttons/_destroy_saved_search.html.erb
<%= link_to saved_search_path(saved_search),
      method: :delete, remote: true, class: 'toolbar-button', title: 'Delete saved search',
      data: { behavior: 'unsubscribe', confirm: "Are you sure you want to delete #{saved_search.name}?" } do %>
  <span class="toolbar-button-inner">
    <%= render partial: "shared/svg/trash" %>
  </span>
  Delete
<% end %>

app/views/shared/buttons/_destroy_tag.html.erb
<% if tag.blank? %>
<div class="toolbar-button" data-behavior="unsubscribe" disabled="disabled">
  <div class="toolbar-button-inner">
    <%= render partial: "shared/svg/trash" %>
  </div>
  Delete
</div>
<% else %>
  <%= link_to tag_path(tag),
        method: :delete, remote: true, class: 'toolbar-button', title: 'Delete tag',
        data: { behavior: 'unsubscribe', confirm: "Are you sure you want to delete #{tag.name}?" } do %>
    <span class="toolbar-button-inner">
      <%= render partial: "shared/svg/trash" %>
    </span>
    Delete
  <% end %>
<% end %>

app/views/shared/buttons/_mark_all_as_read.html.erb
<div class="toolbar-button" disabled="disabled" data-behavior="mark_all_as_read">
  <div class="toolbar-button-inner">
    <%= render partial: "shared/svg/check" %>
  </div>
  Mark Read
</div>

app/views/shared/buttons/_tag.html.erb
<%= content_tag :div, class: 'toolbar-button', data: {behavior: 'show_tags_form'}, disabled: tags.nil? do %>
  <div class="toolbar-button-inner">
    <div class="tags-form-wrap">
      <div data-behavior="tags_form_target" class="tags-form">
        <% if feed.present? %>
          <%= render partial: "feeds/form", locals: {feed: feed, tags: tags, tag: tag} %>
        <% end %>
      </div>
    </div>
    <%= render partial: "shared/svg/tag" %>
  </div>
  Tag
<% end %>

app/views/shared/buttons/_unsubscribe.html.erb
<% if feed.blank? %>
	<div class="toolbar-button" data-behavior="unsubscribe" disabled="disabled">
    <div class="toolbar-button-inner">
      <%= render partial: "shared/svg/trash" %>
    </div>
    Delete
	</div>
<% else %>
	<%= link_to subscription_path(feed.subscription_id),
        method: :delete, remote: true, class: 'toolbar-button', title: 'Unsubscribe',
        data: { behavior: 'unsubscribe', confirm: "Are you sure you want to unsubscribe from #{feed.title}?" } do %>
    <span class="toolbar-button-inner">
      <%= render partial: "shared/svg/trash" %>
    </span>
    Delete
	<% end %>
<% end %>

app/views/shared/buttons/_view_all.html.erb
<%= link_to "All", view_all_feeds_path,
      remote: true, class: "view-button #{view_mode_selected('view_all')}",
      title: 'View all',
      data: { behavior: 'view_all change_view_mode', view_mode: 'view_all' } %>

app/views/shared/buttons/_view_starred.html.erb
<%= link_to "Starred", view_starred_feeds_path,
      remote: true, class: "view-button #{view_mode_selected('view_starred')}",
      title: 'View starred',
      data: { behavior: 'view_starred change_view_mode', view_mode: 'view_starred' } %>

app/views/shared/buttons/_view_unread.html.erb
<%= link_to "Unread", view_unread_feeds_path,
      remote: true, class: "view-button #{view_mode_selected('view_unread')}",
      title: 'View unread',
      data: { behavior: 'view_unread change_view_mode', view_mode: 'view_unread' } %>