config/routes.rb
require 'sidekiq/web'

Feedbin::Application.routes.draw do

  root to: 'site#index'

  mount Sidekiq::Web, at: '/sidekiq'
  mount StripeEvent::Engine, at: '/stripe'

  get :health_check, to: proc {|env| [200, {}, ["OK"]] }
  get :version, to: proc {|env| [200, {}, [ENV["ETAG_VERSION_ID"]]] }

  get :home, to: 'site#home'
  get :apps, to: 'site#apps'

  get :manifest, to: 'site#manifest'

  post '/emails' => 'emails#create'

  match '/404', to: 'errors#not_found', via: :all
  get '/starred/:starred_token', to: 'starred_entries#index', as: 'starred'
  post '/starred/export', to: 'starred_entries#export'
  get '/favicons/:hash', to: 'favicons#index', as: 'favicons'

  get    :signup,         to: 'users#new',           as: 'signup'
  get    :login,          to: 'sessions#new',        as: 'login'
  get    :privacy_policy, to: 'site#privacy_policy', as: 'privacy_policy'
  delete :logout,         to: 'sessions#destroy',    as: 'logout'

  post 'apple_push_notifications/:version/pushPackages/:website_push_id', as: :apple_push_notifications_package, to: 'apple_push_notifications#create', website_push_id: /.*/

  post 'apple_push_notifications/:version/devices/:device_token/registrations/:website_push_id', as: :apple_push_notifications_update, to: 'apple_push_notifications#update', website_push_id: /.*/

  delete 'apple_push_notifications/:version/devices/:device_token/registrations/:website_push_id', as: :apple_push_notifications_delete, to: 'apple_push_notifications#delete', website_push_id: /.*/

  post 'apple_push_notifications/:version/log', as: :apple_push_notifications_log, to: 'apple_push_notifications#log'

  resources :tags,           only: [:index, :show, :update, :destroy]
  resources :billing_events, only: [:show]
  resources :imports
  resources :sessions
  resources :password_resets
  resources :sharing_services, path: 'settings/sharing', only: [:index, :create, :update, :destroy]
  resources :actions, path: 'settings/actions', only: [:index, :create, :new, :update, :destroy, :edit]
  resources :saved_searches

  resources :supported_sharing_services, only: [:create, :destroy, :update] do
    member do
      get :oauth2_pocket_request
      get :oauth2_pocket_response
      get :oauth_response
      get :autocomplete
      post :xauth_request
      match 'share/:entry_id', to: 'supported_sharing_services#share', as: :share, via: [:get, :post]
    end
  end

  resources :subscriptions,  only: [:index, :create, :destroy] do
    collection do
      patch :update_multiple
      delete :destroy_all
    end
    member do
      delete :settings_destroy
    end
  end

  resources :users, id: /.*/ do
    member do
      patch :settings_update, controller: :settings
      patch :view_settings_update, controller: :settings
    end
  end

  resources :feeds, only: [:index, :edit, :create, :update] do
    patch :rename
    resources :entries, only: [:index], controller: :feeds_entries
    collection do
      get :view_unread
      get :view_all
      get :view_starred
      get :auto_update
      get :update_styles
    end
    member do
      match :push, via: [:post, :get]
      post :toggle_updates
      post :toggle_muted
    end
  end

  resources :entries, only: [:show, :index] do
    member do
      post :content
      post :unread_entries, to: 'unread_entries#update'
      post :starred_entries, to: 'starred_entries#update'
      post :mark_as_read, to: 'entries#mark_as_read'
      post :recently_read, to: 'recently_read_entries#create'
      get :push_view
      get :diff
    end
    collection do
      get :starred
      get :unread
      get :preload
      get :search
      get :autocomplete_search
      get :recently_read, to: 'recently_read_entries#index'
      get :updated, to: 'updated_entries#index'
      post :mark_all_as_read
      post :mark_direction_as_read
    end
  end

  get :settings, to: 'settings#settings'
  namespace :settings do
    get :account
    get :billing
    get :import_export
    get :feeds
    get :help
    get :appearance
    post :update_credit_card
    post :mark_favicon_complete
    post :update_plan
    post :font
    post :theme
    post :font_increase
    post :font_decrease
    post :entry_width
  end

  constraints subdomain: 'api' do
    namespace :api, path: nil do
      namespace :v1 do
        match '*path', to: 'api#gone', via: :all
      end
    end
  end

  constraints subdomain: 'api' do
    namespace :api, path: nil do
      namespace :v2 do

        resources :feeds, only: [:show] do
          resources :entries, only: [:index, :show], controller: :feeds_entries
        end

        resources :entry_counts, only: [] do
          collection do
            get :post_frequency
          end
        end

        resources :actions, only: [:index, :create, :update] do
          member do
            get :results
          end
        end

        resources :devices, only: [:create] do
          collection do
            get :test
          end
        end

        resources :users, only: [:create] do
          collection do
            get :info
          end
        end

        resources :subscriptions,         only: [:index, :show, :create, :destroy, :update]
        resources :favicons,              only: [:index]
        resources :tags,                  only: [:index]
        resources :taggings,              only: [:index, :show, :create, :destroy]
        resources :entries,               only: [:index, :show]
        resources :recently_read_entries, only: [:index, :create]
        resources :in_app_purchases,      only: [:create]
        resources :suggested_categories,  only: [:index]
        resources :suggested_feeds,       only: [:index] do
          member do
            post :subscribe
            delete :unsubscribe
          end
        end

        get :authentication, to: 'authentication#index'

        post "subscriptions/:id/update", to: 'subscriptions#update'

        resources :unread_entries, only: [:index, :show, :create]
        delete 'unread_entries', to: 'unread_entries#destroy'
        put 'unread_entries', to: 'unread_entries#create'
        post 'unread_entries/delete', to: 'unread_entries#destroy'

        resources :starred_entries, only: [:index, :show, :create]
        delete 'starred_entries', to: 'starred_entries#destroy'
        put 'starred_entries', to: 'starred_entries#create'
        post 'starred_entries/delete', to: 'starred_entries#destroy'

        resources :updated_entries, only: [:index]
        delete 'updated_entries', to: 'updated_entries#destroy'
        post 'updated_entries/delete', to: 'updated_entries#destroy'

        resources :saved_searches,  only: [:index, :show, :create, :destroy, :update]
        post "saved_searches/:id/update", to: 'saved_searches#update'
      end
    end
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  skip_before_action :authorize, only: [:index, :home, :privacy_policy, :apps, :manifest]
  before_action :check_user, if: :signed_in?

  def index
    if signed_in?
      get_feeds_list
      subscriptions = @user.subscriptions

      user_titles = subscriptions.each_with_object({}) do |subscription, hash|
        if subscription.title.present?
          hash[subscription.feed_id] = ERB::Util.html_escape_once(subscription.title)
        end
      end

      readability_settings = subscriptions.each_with_object({}) do |subscription, hash|
        hash[subscription.feed_id] = subscription.view_inline
      end

      @show_welcome = (subscriptions.present?) ? false : true
      @classes = user_classes
      @data = {
        login_url: login_url,
        tags_path: tags_path(format: :json),
        user_titles: user_titles,
        preload_entries_path: preload_entries_path(format: :json),
        sticky_readability: @user.setting_on?(:sticky_view_inline),
        readability_settings: readability_settings,
        show_unread_count: @user.setting_on?(:show_unread_count),
        precache_images: @user.setting_on?(:precache_images),
        auto_update_path: auto_update_feeds_path,
        font_sizes: Feedbin::Application.config.font_sizes,
        mark_as_read_path: mark_all_as_read_entries_path,
        mark_as_read_confirmation: @user.setting_on?(:mark_as_read_confirmation),
        mark_direction_as_read_entries: mark_direction_as_read_entries_path,
        entry_sort: @user.entry_sort,
        update_message_seen: @user.setting_on?(:update_message_seen),
        feed_order: @user.feed_order
      }

      render action: 'logged_in'
    else
      home
    end
  end

  def home
    @page_view = '/home'
    render action: 'not_logged_in'
  end

  def privacy_policy
    render layout: 'sub_page'
  end

  def apps
    render layout: 'sub_page'
  end

  def manifest; end

  private

  def check_user
    if current_user.suspended
      redirect_to settings_billing_url, alert: 'Please update your billing information to use Feedbin.'
    end
  end

end

app/helpers/site_helper.rb
module SiteHelper
  def resizable(column)
    session[:column_widths] ||= {}
    template = 'data-resizable-name="%s"'
    replacements = [sanitize(column)]
    if session[:column_widths][column]
      template << ' style="width: %ipx"'
      replacements << session[:column_widths][column].to_i
    end
    result = template % replacements
    result.html_safe
  end
end

app/views/site/logged_in.html.erb
<% @class = "app nothing-selected hide-search #{@classes}" %>
<% @behavior = "class_target" %>
<% content_for :head do %>
<meta name="twitter:widgets:link-color" content="#3399FF">
<script>
if (window.feedbin == null) {
    window.feedbin = {};
}
feedbin.data = <%= @data.to_json.html_safe %>;
feedbin.data.viewMode = "<%= @user.get_view_mode %>";
feedbin.count_data = <%= @count_data.to_json.html_safe %>;
feedbin.Counts.get(feedbin.count_data);
</script>
<% end %>
<%= render partial: 'shared/svg' %>

<div class="application-messages"><a href="" class="message-content" data-behavior="messages">You have subscribed</a></div>
<div class="modal-target"></div>

<div class="app-wrap">

    <div class="feeds-column app-panel" data-behavior="content_column" <%= resizable 'feeds' %>>
        <div class="subscribe-toolbar">
            <div class="show-subscribe" data-behavior="show_subscribe">Subscribe</div>
            <%= render partial: 'shared/hamburger_menu_button' %>
        </div>
        <div class="subscribe-wrap">
            <%= form_for :subscription, url: subscriptions_path, remote: true, html: { data: {behavior: 'subscription_form'}, novalidate: 'novalidate' }  do |f| %>
                <%= f.fields_for :feeds do |builder| %>
                    <%= builder.url_field :feed_url, placeholder: 'Feed or URL' %>
                <% end %>
            <% end %>
        </div>
        <div class="feeds-inner">
            <div class="view-toolbar">
                <%= render partial: 'shared/buttons/view_unread' %>
                <%= render partial: 'shared/buttons/view_starred' %>
                <%= render partial: 'shared/buttons/view_all' %>
            </div>
            <div class="feeds" data-behavior="droppable">
                <ul data-behavior="feeds_target">
                    <%= render partial: 'feeds/feeds', locals: {collections: @feed_data[:collections], saved_searches: @feed_data[:saved_searches], tags: @feed_data[:tags], feeds: @feed_data[:feeds]} %>
                </ul>
            </div>
        </div>
        <%= render partial: 'shared/feeds_toolbar' %>
    </div>

    <div class="entries-column app-panel" data-behavior="content_column" <%= resizable 'entries' %>>
        <div class="entries-header" data-behavior="entries-header"></div>
        <div class="entries-inner">
            <%= form_tag search_entries_path, class: 'search-form-wrap', remote: true, method: :get, data: {behavior: 'search_form'} do %>
                <%= search_field_tag :query, params[:query], placeholder: 'Search', autocomplete: 'off' %>
            <% end %>

            <div class="search-control hide">
                <div class="sort-control">
                    <div class="dropdown-wrap">
                        <span class="sort-order" data-behavior="toggle_dropdown">Sort by date</span>
                        <div class="dropdown-content">
                            <ul>
                                <li data-sort-option="desc"><span>Sort by date</span></li>
                                <li data-sort-option="relevance"><span>Sort by relevance</span></li>
                            </ul>
                        </div>
                    </div>
                    <span class="save-search" data-behavior="save_search_link">Save Search</span>
                    <span class="save-search edit" data-behavior="save_search_link">Edit Saved Search</span>
                </div>

                <div class="saved-search-wrap" data-behavior="saved_search_form_target">
                </div>

            </div>

            <div class="entries">
                <ul data-behavior="entries_target"></ul>
            </div>
        </div>
        <%= render partial: 'shared/feeds_toolbar' %>
    </div>

    <div class="entry-column app-panel" data-behavior="content_column">
        <div class="account-toolbar">
            <% if signed_in? && current_user.plan.stripe_id == 'trial' %>
                <%= link_to settings_billing_path, class: 'subscribe-promo' do %>
                    <%= pluralize(current_user.days_left, 'Day') %> Left &mdash; <strong>Subscribe Now</strong>
                <% end %>
            <% end %>
            <div class="entry-buttons">
                <%= render partial: 'shared/app_settings' %>
            </div>
        </div>
        <div class="entry-basement">
            <div class="basement-panel hide" data-basement-panel-target="settings_panel">
                <%= render partial: 'shared/entry_settings' %>
            </div>
            <% @user.supported_sharing_services.each do |service| %>
                <% if service.has_share_sheet? %>
                <div class="basement-panel hide" data-basement-panel-target="<%= service.service_id %>_share_panel">
                    <%= render partial: "supported_sharing_services/share_form_#{service.service_id}", locals: {service: service} %>
                </div>
                <% end %>
            <% end %>
        </div>
        <div class="entry-content-wrap <%= @user.entry_width %> font-size-<%= @user.font_size || 5 %> font-<%= @user.font || 'default' %>" data-font-size="<%= @user.font_size || 5 %>"  data-font="<%= @user.font || 'default' %>" data-behavior="entry_content_target">
        </div>
    </div>

</div>

<div class="hide" data-behavior="pagination"></div>
<%= render partial: "shared/readability_loading" %>
<%= render partial: "shared/keyboard_shortcuts_wrap" %>
<%= render partial: "shared/settings_modal" %>
<%= render partial: "shared/resizable_form" %>
<%= render partial: 'shared/update_styles' %>

<%= one_time_content %>

<%= render partial: 'shared/twitter_embed' %>
<%= render partial: 'shared/instagram_embed' %>

app/views/site/manifest.webapp.erb
{
  "name": "Feedbin",
  "description": "A fast, simple RSS feed reader that delivers a great reading experience.",
  "icons": {
    "32": "<%= asset_path 'firefox-os-icons/logo-32x32.png' %>",
    "60": "<%= asset_path 'firefox-os-icons/logo-60x60.png' %>",
    "128": "<%= asset_path 'firefox-os-icons/logo-128x128.png' %>",
    "256": "<%= asset_path 'firefox-os-icons/logo-256x256.png' %>"
  },
  "developer": {
    "name": "Feedbin, Inc.",
    "url": "https://feedbin.com/"
  },
  "default_locale": "en"
}

app/views/site/not_logged_in.html.erb
<% @class = 'public-page' %>
<% content_for :head do %>
  <meta name="description" content="A fast, simple RSS feed reader that delivers a great reading experience."/>
<% end %>
<div class="header">
  <div class="container">
    <div class="super-header-wrap">
      <div class="row">
        <div class="col-xs-6"><a href="/" class="home-logo hide-text">Feedbin</a></div>
        <div class="col-xs-6 align-right"><%= link_to "Login", login_path, class: "button-login" %></div>
      </div>
    </div>
    <h1 class="tagline"><strong>A fast, simple RSS reader</strong> that delivers a great reading experience.</h1>
    <% if ENV['STRIPE_API_KEY'] %>
        <p class="pricing-promo"><sup>$</sup>3 per month <em>or</em> <sup>$</sup>30 a year</p>
        <p class="align-center"><%= link_to "Try it Free", signup_path, class: "button-get-started" %></p>
    <% else %>
        <p class="align-center"><%= link_to "Sign Up", signup_path, class: "button-get-started" %></p>
    <% end %>
  </div>
  <div class="screenshot-wrap">
      <div class="screenshot-mask">
          <%= image_tag "screenshots/_main_outer.png", width: 1201, height: 684, class: "screenshot-outer" %>
          <%= image_tag "screenshots/_main_inner.jpg", width: 1201, height: 684, class: "screenshot-inner" %>
      </div>
  </div>
</div>
<div class="main-content">
  <div class="container">

    <h2 class="tagline-small">Feedbin syncs with these apps <em><a href="<%= apps_path %>">and more</a></em></h2>
    <div class="apps">
      <a href="https://itunes.apple.com/app/reeder-2/id697846300" class="app clearfix">
        <span class="icon-wrap">
          <%= image_tag 'apps/reeder-iphone.jpg', class: 'icon rounded-icon' %>
        </span>
        <h3>Reeder 2</h3>
        <p>By Silvio Rizzi</p>
      </a>

      <a href="https://itunes.apple.com/app/id911364254" class="app clearfix">
        <span class="icon-wrap">
          <%= image_tag 'apps/unread-iphone.jpg', class: 'icon rounded-icon' %>
        </span>
        <h3>Unread</h3>
        <p>By Supertop</p>
      </a>

      <a href="https://play.google.com/store/apps/details?id=com.twentyfivesquares.press" class="app clearfix">
        <span class="icon-wrap">
          <%= image_tag 'apps/press-android.png', class: 'icon' %>
        </span>
        <h3>Press</h3>
        <p>By TwentyFive Squares</p>
      </a>

      <a href="https://itunes.apple.com/app/mr.-reader/id412874834" class="app clearfix">
        <span class="icon-wrap">
          <%= image_tag 'apps/mr-reader-ipad.jpg', class: 'icon rounded-icon' %>
        </span>
        <h3>Mr. Reader</h3>
        <p>By Oliver Fürniß</p>
      </a>

      <a href="https://itunes.apple.com/app/readkit/id588726889" class="app clearfix">
        <span class="icon-wrap">
          <%= image_tag 'apps/readkit-mac.png', class: 'icon' %>
        </span>
        <h3>ReadKit</h3>
        <p>By Balazs Varkonyi</p>
      </a>

      <p class="sm-show align-center"><%= link_to "See all apps", apps_path %></p>
    </div>

  </div>

  <div class="container align-center">
    <h2 class="tagline-small no-margin">Just what you need in a reader</h2>
    <p class="sub-head">Feedbin is lightweight, you can read for hours on end and it stays out of the way. Feedbin is built for speed with an intuitive layout and keyboard shortcuts to get you where you want to be.</p>

    <div class="col-sm-4 col-sm-push-2 feature">
      <%= image_tag 'icon-home-search.svg', width: '34', class: 'feature-icon-search' %>
      <h3>Search</h3>
      <p>Use Feedbin’s <a href="http://blog.feedbin.com/2013/10/10/search-beta/">advanced search</a> to find just what you’re looking for. <a href="http://blog.feedbin.com/2013/10/14/saved-searches/">Save your searches</a> to save time.</p>
    </div>

    <div class="col-sm-4 col-sm-push-2 feature">
      <%= image_tag 'icon-home-readability.svg', width: '36', class: 'feature-icon-readability' %>
      <h3>Readability</h3>
      <p>Truncated feed content? Built in Readability gets you the full content. Make it sticky to always use Readability for a feed.</p>
    </div>

    <hr class="nospace" />

    <div class="col-sm-4 col-sm-push-2 feature">
      <%= image_tag 'icon-home-share.svg', width: '36' %>
      <h3>Sharing</h3>
      <p>Configurable sharing services let you decide what services you want to use.</p>
    </div>

    <div class="col-sm-4 col-sm-push-2 feature">
      <%= image_tag 'icon-home-tag.svg', width: '36' %>
      <h3>Tags</h3>
      <p>Organize your feeds. Feeds can have as many tags as you need. See all your tagged feeds in Tag Drawers.</p>
    </div>

  </div>

</div>

<div class="developers">
  <div class="container">
    <div class="row">
      <div class="col-md-5">
        <h2 class="tagline-small">API</h2>
        <p class="sub-head">Fully featured, documented API. Feedbin provides access to all your data through a simple JSON API. Get subscriptions, articles and read/starred states and more. </p>
        <p class="sub-head"><a href="https://github.com/feedbin/feedbin-api#readme">Check out the documentation</a> to get started</p>
      </div>
      <div class="col-md-5 col-md-offset-1">
        <%= image_tag 'api-promo.svg', class: 'api-promo responsive' %>
      </div>
    </div>
  </div>
</div>

<%= render partial: "shared/public_footer" %>

app/views/site/privacy_policy.html.erb
<% @title = 'Feedbin Privacy Policy' %>
<div class="main-content">
  <div class="container">
    <h1 class="sub-page">Privacy Policy</h2>
    <p class="large">Privacy is very important to Feedbin.</p>
    <p class="large">SSL is used site-wide. Cookies are used for authentication and session data only. Site cookies are first-party, HTTP only and secure.</p>
    <p class="large">Payment is handled through <a href="https://stripe.com">Stripe</a> so your email address and payment information is shared with them. <a href="https://stripe.com/us/privacy">View their privacy policy</a> for more information. <a href="http://google.com/analytics">Google Analytics</a> is used to collect anonymous analytics data. Your information is never shared with advertisers.</p>
    <p class="large">If you have any questions or concerns about our privacy policies, please contact us: <a href="mailto:support@feedbin.com">support@feedbin.com</a>.</p>
  </div>
</div>